export interface PatientDTO {
    internalID:string;
    patientID:string;
    firstName:string;
    lastName:string;
    middleName:string;
    gender:string;
    civilStatus:string;
    birthDate:string;
    contactNo:string;
    emailAddress:string;
    address:string;
    type:number;
    typeDescription:string;
    status:number;
    statusDescription:string;
    createdDate:string;
    modifiedDate?:string;
}